---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - node_modules/**/*
  - tmp/**/*
  - log/**/*
  - db/schema.rb
  - db/migrate/**/*

require:
  - actioncable
  - actionmailbox
  - actionmailer
  - actionpack
  - actiontext
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
  - rails

domains: []

reporters:
  - rubocop
  - require_not_found

formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []

require_paths: []

plugins:
  - solargraph-rails

max_files: 5000
